version: '3.3'

services:

    web:
        build: .
        container_name: fastapiwebsocket
        restart: unless-stopped
        command: uvicorn --host 0.0.0.0 run:app
        ports:
            - "8000:8000"
