version: '3.3'

services:

    web:
        build: .
        container_name: fastapi_test_tasks
        restart: unless-stopped
        command: python run.py
        ports:
            - "8000:8000"
